### ISSUE TITLE
First course page deleted -> course can't be shared / embedded

### ISSUE THREAD

**Issue by ghost** [serlo/cloudflare-worker#170]
E.g. this course: https://de.serlo.org/mathe/20368/%C3%BCberblick

If you embed this course in a folder or share the link you get the id of the former first course page which has been deleted.
-> https://de.serlo.org/19479

**Comment by inyono** [comment]
I guess the long-term solution would be to add a  `trashed` filter to `pages`, so that we can easily query the first non-trashed course page.

**Comment by kulla** [comment]
@yolo-bird Thanks for reporting! A bug fix is on the way (linked to this issue)
