### ISSUE TITLE
Potential alias bug

### ISSUE THREAD

**Issue by inyono** [serlo/cloudflare-worker#196]
See https://sentry.io/organizations/serlo/issues/2197370521/?project=5206333&query=is%3Aunresolved

https://de.serlo.org/mathe/geometrie/grundbegriffe/geraden-strecken-halbgeraden/strecke gets not redirected to a new alias and is rendered in legacy.

**Comment by kulla** [comment]
Okay, the redirect works now. However I have found some other weird bugs I have to investigate (currently needed information are filtered out but I have changed the config in Sentry and I wait for new events to do more...)

**Comment by kulla** [comment]
Close issue since the redirect works right now...
