### ISSUE TITLE
Change useFrontend logic

### ISSUE THREAD

**Issue by elbotho** [serlo/cloudflare-worker#262]
Should we replace the `useFrontend` cookie with a simple `useLegacyFrontend` cookie (set to 1) that is just removed when people use `/enable-frontend` again? 
I think this would fit our current approach better and might simplify code.

@kulla what do you think?

PS: just now I was sure setting `useFrontend` to `0` should deactivate the new frontend. very confusing 🤔

**Comment by elbotho** [comment]
If you agree I'd probably start a PR (ping @kulla)

**Comment by kulla** [comment]
Do you mean: `frontend` is the default and only when `useOldDesign === 1` the old design is used? (I am on board with this idea...)

**Comment by elbotho** [comment]
>Do you mean: frontend is the default and only when useOldDesign === 1 the old design is used? (I am on board with this idea...)

Yea, that's the idea. I don't think we need a propability based approach any more for this. I'd prefere a binary switch.
