### ISSUE TITLE
trigger sentry when legacy is used

### ISSUE THREAD

**Issue by elbotho** [serlo/cloudflare-worker#337]
@kulla maybe cf worker is the best place for this?
This way we can keep track of all routes that might still be relied upon.

**Comment by kulla** [comment]
When #317 is deployed we already now all paths which go to frontend. These are the ones in https://github.com/serlo/cloudflare-worker/blob/279-change-frontend-proxy-default/src/frontend-proxy.ts#L165-L184 -> So which other things shall be tracked?

**Comment by elbotho** [comment]
Basically I want to see every time legacy is accessed (even with "disable-frontend"). Just for peace of mind :)
