### ISSUE TITLE
kratos: verification and recovery in staging not working

### ISSUE THREAD

**Issue by elbotho** [serlo/cloudflare-worker#340]
> Besides that, the verification in staging is not working. 500 at `api/.ory/self-service/verification`
(by @hugotiburtino )

(Probably CF-Issue)

**Comment by hugotiburtino** [comment]
After clicking the link in the recovery or verification email, you get a 500. It works in localhost and worked before in staging when it was not proxied by cloudflare.
It was supposed to do the following:
1. after clicking the link, frontend makes an api call in path `.ory/self-service/...` to kratos instance.
2. kratos redirects the user to frontend's correct path (v.g. `auth/verfirication`) with the correct response. 
3. cloudflare follow the redirect.
4. user comes to the correct path.

It is failing at 3.

**Comment by elbotho** [comment]
This works now I think. Only remaining issues I have is with the instances:
https://github.com/serlo/frontend/issues/1907

**Comment by hugotiburtino** [comment]
> This works now I think. Only remaining issues I have is with the instances

Yes, it is not related to cloudflare worker, they were/will be handled elsewhere (api/kratos)
